<? php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->';
echo '';
echo '';
echo '<title>Modern & Minimal Resume / CV & vCard Template</title>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'CSS Stylesheets';
echo '=====================================================-->';
echo '<link rel='stylesheet' type='text/css' href='bootstrap/css/bootstrap.min.css' >';
echo '<link rel='stylesheet' type='text/css' href='css/linea.css' >';
echo '<link rel='stylesheet' type='text/css' href='css/ionicons.min.css' >';
echo '<link rel='stylesheet' type='text/css' href='css/owl.carousel.css' >';
echo '<link rel='stylesheet' type='text/css' href='css/magnific-popup.css' >';
echo '<link rel='stylesheet' type='text/css' href='css/style.css' >';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'Preloader';
echo '=====================================================-->';
echo '<div id='preloader' >';
echo '<div class='loader' ></div>';
echo '<div class='left' ></div>';
echo '<div class='right' ></div>';
echo '</div>';
echo '';
echo '';
echo '<div class='main-content' >';
echo '';
echo '<!--=====================================================';
echo 'Page Borders';
echo '=====================================================-->';
echo '<div class='page-border border-left' ></div>';
echo '<div class='page-border border-right' ></div>';
echo '<div class='page-border border-top' ></div>';
echo '<div class='page-border border-bottom' ></div>';
echo '';
echo '';
echo '';
echo '<!--=====================================================';
echo 'Menu Button';
echo '=====================================================-->';
echo '<a href='#' class='menu-btn' >';
echo '<span class='lines' >';
echo '<span class='l1' ></span>';
echo '<span class='l2' ></span>';
echo '<span class='l3' ></span>';
echo '</span>';
echo '</a>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'Menu';
echo '=====================================================-->';
echo '<div class='menu' >';
echo '<div class='inner' >';
echo '<ul class='menu-items' >';
echo '';
echo '<li>';
echo '<a href='#' class='section-toggle' data-section='intro' >';
echo 'Home';
echo '</a>';
echo '</li>';
echo '';
echo '<li>';
echo '<a href='#about' class='section-toggle' data-section='about' >';
echo 'About';
echo '</a>';
echo '</li>';
echo '';
echo '<li>';
echo '<a href='#portfolio' class='section-toggle' data-section='portfolio' >';
echo 'Class Works';
echo '</a>';
echo '</li>';
echo '';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class='animation-block' ></div>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'Sections';
echo '=====================================================-->';
echo '<div class='sections' >';
echo '';
echo '<!--=====================================================';
echo 'Main Section';
echo '=====================================================-->';
echo '<section id='intro' class='section section-main active' >';
echo '';
echo '<div class='container-fluid' >';
echo '';
echo '<div class='v-align' >';
echo '<div class='inner' >';
echo '<div class='intro-text' >';
echo '';
echo '<h1>Yeshua Cagatan</h1>';
echo '';
echo '<p>';
echo 'My USERDES website';
echo '</p>';
echo '';
echo '<div class='intro-btns' >';
echo '';
echo '<a href='#about' class='btn-custom section-toggle' data-section='about' >';
echo 'About me';
echo '</a>';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'About Section';
echo '=====================================================-->';
echo '<section id='about' class='section about-section border-d' >';
echo '';
echo '<div class='section-block about-block' >';
echo '<div class='container-fluid' >';
echo '';
echo '<div class='section-header' >';
echo '<h2>';
echo 'Hi, im <strong class='color' >Yeshua</strong>';
echo '</h2>';
echo '</div>';
echo '';
echo '<div class='row' >';
echo '';
echo '<div class='col-md-4' >';
echo '';
echo '<ul class='info-list' >';
echo '';
echo '<li>';
echo '<strong>Name:</strong>';
echo '<span>Yeshua Cagatan</span>';
echo '</li>';
echo '';
echo '<li>';
echo '<strong>Occupation:</strong>';
echo '<span>ABMA Student</span>';
echo '</li>';
echo '';
echo '<li>';
echo '<strong>Age:</strong>';
echo '<span>20 Years</span>';
echo '</li>';
echo '';
echo '<li>';
echo '<strong>Hometown:</strong>';
echo '<span>Paranaque</span>';
echo '</li>';
echo '';
echo '';
echo '';
echo '</ul>';
echo '';
echo '</div>';
echo '';
echo '<div class='col-md-8' >';
echo '';
echo '<div class='about-text' >';
echo '<p>';
echo 'Hi! I’m Yeshua, it’s a Hebrew name pronounced as “Ye-shu-wa”, but people mostly pronounce it as “Yesh-wa” but im fine with any as long as I know it’s my name~';
echo 'degree in Aircraft Maintenance and Technology. I’m a quiet person but not a shy one, I just don’t start conversations I guess? I usually';
echo 'spend my free time playing video games, or going out and trying new stuff. I often go hiking/trekking. I also like learning new things,';
echo 'I learn things fast if it interests me~  In this class im expecting to learn the things needed to design things. Basically, how I should';
echo 'design things, what I should include and why.';
echo '</p>';
echo '';
echo '<p>';
echo 'In this USERDES class i expect to learn the basics of html coding and how to create or design a user interface. :)';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class='section-block services-block' >';
echo '';
echo '<div class='container-fluid' >';
echo '';
echo '<div class='section-header' >';
echo '';
echo '<h2>My <strong class='color' >Favorite Apps</strong></h2>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<div class='row' >';
echo '';
echo '<div class='col-md-4' >';
echo '<div class='service' >';
echo '';
echo '<div class='icon' >';
echo '<i class='icon-music-note-multiple' ></i>';
echo '</div>';
echo '';
echo '<div class='content' >';
echo '';
echo '<h4>Music</h4>';
echo '';
echo '<p>';
echo 'There are a lot of music apps available but the best one for me is Spotify because its interface is userfriendly, easy to understand and easy to use.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class='col-md-4' >';
echo '<div class='service' >';
echo '';
echo '<div class='icon' >';
echo '<i class='icon-basic-world' ></i>';
echo '</div>';
echo '';
echo '<div class='content' >';
echo '';
echo '<h4>Social</h4>';
echo '';
echo '<p>';
echo 'Social media apps are becoming a necessity for communication nowadays. The best social media app for me is probably Facebook because I think it was the 1st sociak media app that I used and i've gone used to it.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class='col-md-4' >';
echo '<div class='service' >';
echo '';
echo '<div class='icon' >';
echo '<i class='icon-basic-joypad' ></i>';
echo '</div>';
echo '';
echo '<div class='content' >';
echo '';
echo '<h4>Games</h4>';
echo '';
echo '<p>';
echo 'There arent a lot of gaming platforms available, or maybe I havent heard of a lot others but for me Steam is the one I like the most, beacuse unlike the otehrs its interface is really simple and it continues to update every now and then.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class='section-block skills-block' >';
echo '<div class='container-fluid' >';
echo '';
echo '<div class='section-header' >';
echo '';
echo '<h2>';
echo 'My <strong class='color' >Skills</strong>';
echo '</h2>';
echo '';
echo '</div>';
echo '';
echo '<div class='row' >';
echo '';
echo '<div class='col-md-6' >';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>HTML/CSS</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:35%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>video editing</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:90%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>Audio Editing</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:85%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class='col-md-6' >';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>Photoshop</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:80%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>Illustrator</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:80%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class='skill' >';
echo '';
echo '<h4>Digital Painting</h4>';
echo '';
echo '<div class='bar' >';
echo '<div class='percent' style='width:70%;' ></div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'Portfolio Section';
echo '=====================================================-->';
echo '<section id='portfolio' class='section portfolio-section border-d' >';
echo '';
echo '<div class='section-block portfolio-block' >';
echo '';
echo '<div class='container-fluid' >';
echo '';
echo '';
echo '<div class='section-header' >';
echo '<h2>My <strong class='color' >Class Works</strong></h2>';
echo '</div>';
echo '';
echo '<ul class='portfolio-filters' >';
echo '<li>';
echo '<a href='#' class='active' data-group='all' >';
echo 'All';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href='#' data-group='reflection' >';
echo 'Reflections';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href='#' data-group='activity' >';
echo 'Activities';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href='#' data-group='quiz' >';
echo 'Quizzes';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '<ul class='portfolio-items' >';
echo '';
echo '<li data-groups='["reflection"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/1.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-1' class='view-project' >';
echo 'View Reflection';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-1' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>My first week in USERDES</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'I was having a hard time arranging my schedule for the term, because most of the remaining subjects that I have, have conflict in schedule and so I had to choose which ones I should take now and which ones would be offered again in the next incoming term. It took me the whole week fixing this and so I was removed in some of my registered subjects and that’s why I was a late enrollee. I started during the second week of classes and I think I missed 3 meetings already? Because of this I had a hard time catching up with what the class was currently working on and on top of that, everyone in the class was an unfamiliar face even the instructor so I find it hard to approach them and ask about the activities in class. The instructor was very nice and approachable and helped me interact with my classmates and at the end of the day I saw how approachable and friendly everyone was and that they were willing to help if I just ask.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["reflection"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/2.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-2' class='view-project' >';
echo 'View Reflection';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-2' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>My First Web Application using Github and Heroku</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'Im kinda new with coding, I literally know nothing about it and how it works so I kinda find it hard to understand at first. But after reading the resources provided and watching a dozen of vids online on the basics and how to create a simple web application, I slowly began to understand how the codes work and what they do. I still find some of the codes hard to understand especially if an error appears, I find it kinda hard to understand on what it wants for the error to disappear but after searching for a solution for them in the internet and asking some of my classmate’s or the instructor, I am able to make it work. Although until know I still haven’t fully understood on how to deploy the web app online. But even after all these I find it very satisfying whenever I try something new and it actually works.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["quiz"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/03_Q1_1st_Cagatan.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-3' class='view-project' >';
echo 'View Quiz';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-3' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/03_Q1_1st_Cagatan.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>My 1st try in Userinyerface</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '';
echo '<li data-groups='["reflection"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/4.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-4' class='view-project' >';
echo 'View Reflection';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-4' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>Userinyerface experience</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'The Userinyerface is probably the worst UI I’ve ever encountered. At first, it looked like a normal sign up page with bad design, but then it gets worse. The buttons doesn’t exactly do what you think it should do, sometimes it even does the complete opposite. There are also annoying pop ups that appear which when I try to get rid off becomes even more annoying. So instead of getting rid of it, I just refresh the page and restart all over again which kinda makes it frustrating. But even so, I guess it was kinda fun and I managed to finish it.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["activity"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/5.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-5' class='view-project' >';
echo 'View Activity';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-5' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/21-futuristic-glass-elevator-and-building-kit-daz3d.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>Elevator for a 1000 floor building</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'If I were to design an elevator for a 1000 floor building, I would prioritize its user’s convenience. Since an elevator takes an average of 2sec to go up a floor and another 3-6 seconds for the door to stay open, it would take it a few minutes to go up a couple of floors and having a building with 1000 floor the users might find it uncomfortable staying inside that enclosed space. So if I would design an elevator for that kind of situation, I would probably make it a bit bigger. The usual elevator size usually has a measurement of approximately of 6-7ft wide 5-6ft deep (front to back) and around 8ft high, but I would make mine almost double of that size, around  12ft wide 9-10ft deep and with a height of 9ft. I would add a place for them to sit on the sides with comfortable cushions and provide calming elevator music to keep them entertained while inside. I would also include air purifier that would provide a good scent that would quickly eliminate bad odor inside the enclosed space. The building would have several of these elevators, 1 for VIP use, another for people with disabilities, the elderly and the pregnant, (which would be accompanied with an elevator staff in case of emergency and also to assist them), another for the building staff, 4 for resident use and 2 for visitor use. The keypad inside the elevator would be a digital touchscreen.';
echo '</p>';
echo '<p>But instead would only include numbers and a button for emergency, enter, delete, close and open (for the elevator doors). Upon reaching a desired floor the floor number would be mentioned in the elevator speaker and the floor number would appear on the elevator doors where everyone inside would be able to see clearly. The elevators would also have a card reader feature, where residents, staff and people in the building could use using their cards/id’s and they would just tap it and the elevator would suggest a floor number where the user currently resides or usually goes. The elevator would record the user’s usual floor that they entered so that the user would just simply click one of the floor numbers instead of typing it.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["quiz"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/03_Q1_3rd_Cagatan.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-6' class='view-project' >';
echo 'View Quiz';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-6' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/03_Q1_3rd_Cagatan.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>My 2nd try in Userinyerface</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["activity"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/3.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-7' class='view-project' >';
echo 'View Activity';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-7' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/3jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>PETAGRAM</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'In the brainstorming of the project, we, the proponents discuss our common thing and we come up about the things that we care and what make us entertain in our free time. With this, we notice our common thing which is our affection and interest to our pets and other animals and from here we try to discuss what we want and that is too surf the net with only pets and animals in our feeds or walls.';
echo 'In here, the issue and the problem regarding shelters that beg for donations rise up and animal situation from the zoo, laboratories, shelters and streets were also notice. As we want to answer this problem, we thought of something where people’s attention can be caught easily, and that is through social media. However, social media is a wide platform so we think of a way to narrow it down and that is by restricting a social media for animals and pets that leads to PETAGRAM.';
echo 'Other solution we suggest is to make a simple website or platform where people can find shelters to donate or be a volunteer. Just like how grab car works, this platform is for finding a nearest shelter where they can send help. However, this idea will not work based on our observation. As a group, we observed that people will just surf or read an information if there is a video or picture included to the information. We also observed that people are more active when it comes to socializing, talking to another user or having someone new as a friend. This observation soon leads to the idea of the PETAGRAM.';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["activity"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/6.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-8' class='view-project' >';
echo 'View Activity';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-8' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/6jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>Favorite Applications</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo 'A lot of different applications are used every day, and my favorite ones I guess are YouTube, Facebook and Spotify. I started using these apps way back, around several years ago I think? Or maybe more. I only started using Facebook for communication purposes but now I probably also use it for entertainment like YouTube, where I watch videos, to learn stuff, to listen to music or simply just watch random videos. The Spotify app on the other hand, is the best music app for me, where I could listen to millions of songs. These are the apps that I always use and I believe helps me in my everyday life to relax or to serve as entertainment when I’m bored.';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '<li data-groups='["activity"]' >';
echo '<div class='inner' >';
echo '<img src='img/portfolio/grids.jpg' alt>';
echo '';
echo '<div class='overlay' >';
echo '';
echo '<a href='#popup-9' class='view-project' >';
echo 'View Activity';
echo '</a>';
echo '';
echo '<!--project popup-->';
echo '<div id='popup-9' class='popup-box zoom-anim-dialog mfp-hide' >';
echo '<figure>';
echo '';
echo '<!--project popup image-->';
echo '<img src='img/portfolio/grids.jpg' alt>';
echo '';
echo '</figure>';
echo '<div class='content' >';
echo '';
echo '<!--project popup title-->';
echo '<h4>GRIDS</h4>';
echo '';
echo '<!--project popup description-->';
echo '<p>';
echo '';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</li>';
echo '';
echo '';
echo '</ul>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<!--=====================================================';
echo 'JavaScript Files';
echo '=====================================================-->';
echo '<script src='js/jquery.min.js' ></script>';
echo '<script src='js/jquery.shuffle.min.js' ></script>';
echo '<script src='js/owl.carousel.min.js' ></script>';
echo '<script src='js/jquery.magnific-popup.min.js' ></script>';
echo '<script src='js/validator.min.js' ></script>';
echo '<script src='js/script.js' ></script>';
echo '';
echo '</body>';
echo '</html>';
?>